### ISSUE TITLE
Module 2: Introduction (Who Why What)

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#10]
**Milestone:** Community

**Description**
Creating the content for the "Community folks" subsection.

**Sub-tasks**
- [x]  "Who are we?" unit
- [x]  "Why are we here?" unit
- [x]  "What do we do?" unit

**Definition of Done**
The initial version of the "Community folks" subsection is published.

**Comment by sarina** [comment]
It didn't feel like enough info for this to be three separate units. I made one, called [Who, Why, and What?](https://studio.edunext.co/container/block-v1:tCRIL+OE101+2022+type@vertical+block@9cbed835656449cb94b2809857adcf70) - could you review?

**Comment by jalondonot** [comment]
Approved FMPOV!

**Comment by mariajgrimaldi** [comment]
This took me some time 😅 . Thanks Sarina for all the work! I reviewed this as if I was taking the course and I have just a few comments:
1. Should we continue mentioning _devstack_ in the openedx.org > community > develop section? should we also add react as a technology?
![image](https://user-images.githubusercontent.com/64440265/234711071-f433b5bc-8f72-4dac-ad6b-8664e18ee5ff.png)
2. The docs link from the openedx.org develop section is pointing to: https://docs.edx.org/openedx.html which doesn't exist
![image](https://user-images.githubusercontent.com/64440265/234713658-2d01d155-3273-4863-a2ae-e7ab3937f18c.png)
3. The github link from the openedx.org develop section is pointing to https://github.com/edx instead of https://github.com/openedx
4. We're still talking about devstack in the openedx.org develop section:
![image](https://user-images.githubusercontent.com/64440265/234714035-485c20e3-410a-42e9-8781-be06099f6137.png)
5. Can we add a blank line here? and in the other title section
![image](https://user-images.githubusercontent.com/64440265/234714394-bfa13608-0fef-4ab7-9f2f-59adec60fde6.png)

I understand most of my comments relate to the resource openedx.org, but I just wanted to leave that somewhere so we can report it later.

**Comment by sarina** [comment]
It's good feedback @mariajgrimaldi - those pages haven't been reviewed in forever. I didn't write the first pass at this material, and I was not very sure if linking to openedx.org would be useful at all given how outdated it is. I'm not sure I can get these pages updated - would it be better to just not link to openedx.org?

**Comment by sarina** [comment]
Just noting this is blocked on the broken WordPress site. Once that's fixed I'll adjust the page and close this ticket out.

**Comment by sarina** [comment]
Updated the openedx.org Develop page. If you see other pages that need editing just let me know!
