### ISSUE TITLE
Community dynamics Subsection

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#12]
**Milestone:** Community

**Description**
Creating the content for the "Community dynamics" subsection.

**Sub-tasks**
- [ ]  "Working groups" unit
- [ ]  "Named releases" unit
- [ ]  "Technical Oversight Committee" unit
- [ ] "Open edX Conference & monthly meetups" unit
- [ ] "Core contributor program" unit
- [ ] "Maintainership program" unit

**Definition of Done**
The initial version of the "Community dynamics" subsection is published.

**Comment by sarina** [comment]
This was moved under the "Join Us" section; if there's disagreement, we can discuss it as part of review of #14
