### ISSUE TITLE
Module 2: Getting help Subsection

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#13]
**Milestone:** Community

**Description**
Creating the content for the "Getting help" subsection.

**Sub-tasks**
- [x]  "Community channels" unit
- [x]  "Community working groups" unit
- [x] "Other resources" unit

**Definition of Done**
The initial version of the "Getting help" subsection is published.

**Comment by sarina** [comment]
This is ready for review

**Comment by jalondonot** [comment]
Not much to add here. Liking it so far! From reviewing this course I'm actually learning things I didn't know about the Community 😂

Just a little suggestion for the "Community channels" unit - "Q: I'm a course author/educator. Are there any community resources available to me about running a course?". Shouldn't we be more explicit about our brand new educators WG? I know it is indirectly aforementioned, but maybe we could highlight it since, I think, many people would be interested in being part of it. What do you think, @sarina @mariajgrimaldi ?

**Comment by mariajgrimaldi** [comment]
I wish we had a question about finding bugs or software malfunctions. What do you think? Something similar about finding a maintainer but simpler:
Q: What if I find a bug?
A: Send a message on slack or create a post on discuss describing in detail your issue! Remember to use the correct channel which depends on the issue you're having.

**Comment by sarina** [comment]
thanks for the review! Agree that the bug question is covered in Module 3. I added a link to Module 3 in the developer question in the q&a
