### ISSUE TITLE
2023-01-27 Meeting Notes & To-Dos

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#24]
### Meeting notes

- The Community Onboarding Module 1 is almost done. We got some feedback from Sarina and we decided to move the Platform Architecture unit to the Code Contribution unit. The platform overview section will focus on the product rather than the technical part
- The first version of the Core contributor Onboarding course is ready.

### To-Dos

- [x] @sarina will review the first 2 subsections of the first module
- [x] @sarina will finish the welcome video for the CC onboarding course (https://github.com/openedx/training-courses/issues/21)
- [x] @sarina will add the banner image for the site (https://github.com/openedx/training-courses/issues/23)
- [x] @sarina will, if possible, create a course card image for the Community onboarding course (https://github.com/openedx/training-courses/issues/23)
- [x] @mariajgrimaldi and @jalondonot will work on applying Sarina's feedback to the introduction and Module 1 sections
- [ ] @mariajgrimaldi and @jalondonot will finish the module 2
