### ISSUE TITLE
2023-02-27 Meeting Notes & To-Dos

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#26]
### Meeting notes

- 

### To-Dos

- [x] @sarina write "Join Us!" section (wg link to resolve https://github.com/openedx/training-courses/issues/8)
- [x] @sarina get the test eng course on the instance, and link to it from first part of our course
- [x] @sarina link the Open Source course in the first module https://courses.opencraft.com/courses/course-v1:MOOC-FLOSS+101+2021_1/courseware/chap-01/chap-01-seq-01/?activate_block_id=block-v1%3AMOOC-FLOSS%2B101%2B2021_1%2Btype%40sequential%2Bblock%40chap-01-seq-01
- [x] @mariajgrimaldi going to combine "Meet the Community" and "About Us" section
- [ ] @jalondonot will provide review for Sarina & Majo next week

Later: Survey block at the end (@mariajgrimaldi will figure out 🙂 )

Later: add "check your understanding" question banks for each module

**Comment by sarina** [comment]
I got the demo course uploaded to the training instance, but then I realized we need to rename the organization from "tCRIL" to "Axim". I've asked my team the best way to do this & will work with the eduNEXT support team to make it happen. So... don't make any new courses until this is sorted out!

**Comment by sarina** [comment]
Ready for review, as said in email (module 1 & 2; not sure what I should do yet with module 3)

**Comment by sarina** [comment]
Closing this ticket; the open to-do is tracked on #29
