### ISSUE TITLE
2023-04-25 Meeting Notes & To-Dos

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#29]
**### To-Dos**

**Module 1**
- [ ] @mariajgrimaldi @jalondonot will review [What's next?](https://github.com/openedx/training-courses/issues/9#issuecomment-1506018848)
- [ ] @mariajgrimaldi @jalondonot will review [Meet the community Subsection](https://github.com/openedx/training-courses/issues/11)

**Module 2**
- [x] @mariajgrimaldi @jalondonot will review [Community folks Subsection](https://github.com/openedx/training-courses/issues/10)
- [x] @mariajgrimaldi @jalondonot will review [Community dynamics Subsection](https://github.com/openedx/training-courses/issues/12#issuecomment-1506014080)
- [ ] @mariajgrimaldi @jalondonot will review [Getting help Subsection](https://github.com/openedx/training-courses/issues/13)
- [ ] @mariajgrimaldi @jalondonot will review [Join us Subsection](https://github.com/openedx/training-courses/issues/14)
- [ ] @mariajgrimaldi @jalondonot will review [What's next?](https://github.com/openedx/training-courses/issues/28)

**Module 3**
- [x] @sarina will work on #15 
- [x] @sarina will work on #16 
- [x] @sarina will work on #30 
- [x] @sarina will work on #31 

**Course Overall**
- [x] @sarina will move all the courses to Axim's org
- [ ] Launching the course!

**Comment by mariajgrimaldi** [comment]
What I've reviewed so far:
Module 1:
- What's next?
- Meet the community
Module 2:
- Community folks 
- Join us 
- What's next

**Comment by sarina** [comment]
:mega: I have moved all the courses to new homes, under the “Axim” org

<img width="580" alt="image" src="https://user-images.githubusercontent.com/1985317/234995581-a920198f-f6a9-4a42-84fe-669cf37e603b.png">

be sure to use the new ones!

**Comment by sarina** [comment]
I went through @mariajgrimaldi 's feedback and have some more questions about that. Tomorrow is my last day in the office so if you have any other feedback by tomorrow I'll address it!

**Comment by sarina** [comment]
I finished Module 3, but it _definitely_ needs feedback. Please take a look when you can.
