### ISSUE TITLE
5/31/23 ASU - Axim meeting

### ISSUE THREAD

**Issue by sarina** [openedx/training-courses#48]
Before June 27 meeting:

Elizabeth

- [x] Verify Farhaan's ability to spend time on project

- [x] Let Sarina know how many hours Farhaan has to work on it

Christy

- [ ] Take a spin through the Intro course: does it work for you / is anything missing / does it serve as a good prerequisite to the Dev and Site Operator onboarding courses?

Sarina

- [x] Re-organize Onboarding document into structured sub-docs and folders #51 
- [x] Objectives for each module #52
- [x] Write tickets for module content on our project tracker (here: https://github.com/orgs/openedx/projects/15 - we'll use this for engineering tasks and you're welcome to use it if it's helpful)
- [x] Delegate some content to the eduNEXT team (and Farhaan, if available)
- [x] Write out rough plan for project timeline - https://docs.google.com/spreadsheets/d/1h6YQGQeIGf-45PGqmlHbZBNDeuEdmVoB7RUtaOeozMY/edit#gid=0
- [x] Write content for Introduction #53
- [x] Write content for Module 1 #37 
- [ ] (things for post-June include recording screencasts and delivering a "training" Open edX logo)

**Comment by sarina** [comment]
I connected with Farhaan and he will be able to use some core contributor hours to make some headway on the project.
