### ISSUE TITLE
About Open edX Subsection

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#7]
**Milestone:** The Open edX Project

**Description**
Creating the content for the "About Open edX" subsection.

**Sub-tasks**
- [ ]  "What is Open edX?" unit
- [ ]  "A bit of history" unit
- [ ] "Open edX today" unit

**Definition of Done**
The initial version of the "About Open edX" subsection is published.

**Comment by mariajgrimaldi** [comment]
assign me

**Comment by sarina** [comment]
Hi!

I made some edits as follows:

* on Module 1 - The Open edX Project - Introduction: I corrected some typos, added a few more examples of who uses the software, and corrected usage of "Open edX" - for your reference, "Open edX" is an adjective so it must always be followed by a noun (like, "the Open edX project" or "the Open edX software"). I also clarified that tCRIL doesn't run the project, we steward it. Our goal is that the community will run it!

* About Open edX - What Is Open edX?: I made some small corrections to spelling. I think in Sergey's quote you should remove this sentence: "But before we dive into the features of Open edX, we’ll briefly describe its history and how it compares with other learning management systems."

* About Open edX - History: Love it! I added a bullet about expanding the CC program to a bunch of roles, and a sentence on the bottom that covers what we're doing now. If you wanted you could add more details, but I thought it would probably be good at this time to be more high level.
* About Open edX - Open edX project today: Looks great! I fixed a typo that I had made in the original survey... 🙈 

I think that's all I needed to review here, right? I don't think you need to change much here. I wonder if you want to try to add some images on some of these pages. For example I could probably make something fun for the History Overview, if you'd like.

**Comment by mariajgrimaldi** [comment]
Corrected! Thank you so much Sarina 🥇

**Comment by sarina** [comment]
Yay! I think this is done now so I'm going to close the ticket.... 🎉 🦖
