### ISSUE TITLE
Product Overview Subsection

### ISSUE THREAD

**Issue by jalondonot** [openedx/training-courses#8]
**Milestone:** The Open edX Project

**Description**
Creating the content for the "Platform overview" subsection.

**Sub-tasks**
- [ ]  "Product offering" unit
- [ ]  "Tech stack" unit
- [ ]  "Platform core" unit
- [ ] "Extensions" unit

**Definition of Done**
The initial version of the "Platform overview" subsection is published.

**Comment by mariajgrimaldi** [comment]
assign me

**Comment by mariajgrimaldi** [comment]
Currently working on "Tech Stack" unit while I wait for answers for the "About the Open edX project" form.

**Comment by sarina** [comment]
Hi! I changed the title of this to Product Overview.

**Can you please move the last unit to module 3?**

I added a first unit called "Defining Product" and rewrote the product offerings section to be more accessible. I wrote the OEP-57 so probably easier for me to figure out how to summarize this. I'm also going to add a more simplified diagram. **Can you please review these?**

I was thinking of adding a third section about the Product Working Group and how to get involved if this interests you. How does that sound?

Finally, **what images or other stuff could we add to make this more interesting?**

**Comment by mariajgrimaldi** [comment]
Hello! I moved the architecture unit to module 3! Thanks for the reminder.

> Can you please review these? Is the third unit too complicated?

This is great content! Just a short note on the last unit, so it is more beginner-friendly:

> behind the scenes code that lets you use extensions like XBlocks and LTI 
Could we add links for Xblocks and LTI docs? I feel that a newcomer wouldn't know what these extensions are. Same comment for the bundled extensions.

> I was thinking of adding a fourth section about the Product Working Group and how to get involved if this interests you. How does that sound?

[There's a section](https://studio.edunext.co/container/block-v1:tCRIL+OE101+2022+type@vertical+block@45e4bd12119e41d498442305050c6273) in the Community module where we include a list of all the wg with relevant info, do you think we could add that there? Or is it better right there on the product overview?

**Comment by mariajgrimaldi** [comment]
@sarina I like the idea of a 4th section! 🥇

**Comment by sarina** [comment]
Great! I'm going to leave this ticket open until we write the Working Groups unit, so that I remember to link to it from this section.
